### ISSUE TITLE
feature request - add Cognito into the mix

### ISSUE THREAD

**Issue by mitni455** [jakejscott/aws-cdk-phone-verify-api#1]
Feature request - Add Cognito into the stack too so you can programatically verify User Pools

**Comment by jakejscott** [comment]
Yeah could totally do that. At the moment I've just secured it using API Gateway API Keys. 

I envisioned this api would be a private microservice that would be available to other services in an application. So you'd have some kind of public facing api for your mobile/web app that would could consume this. 

Cognito actually has SMS MFA and I would recommend using that if you can over this service if you can use it.
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-sms-text-message.html
